### ISSUE TITLE
Excessive wait time during loading

### ISSUE THREAD

**Issue by mtrevor** [K-4U/Hydraulicraft#119]
I'm running Hydcraft 2.0.87 under Minecraft 1.7.10.

My launch times had suddenly grown significantly, the logs show it's a connection time out issue:

    [14:14:24] [Client thread/TRACE] [HydCraft/HydCraft]: Sending event FMLInitializationEvent to mod HydCraft
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.net.SocketException: Connection reset
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.SocketInputStream.read(SocketInputStream.java:189)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.SocketInputStream.read(SocketInputStream.java:121)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:703)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:674)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1534)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URL.openStream(URL.java:1038)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at k4unl.minecraft.Hydraulicraft.lib.UpdateChecker.readUrl(UpdateChecker.java:66)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at k4unl.minecraft.Hydraulicraft.lib.UpdateChecker.checkUpdateAvailable(UpdateChecker.java:29)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at k4unl.minecraft.Hydraulicraft.Hydraulicraft.load(Hydraulicraft.java:121)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    [14:20:42] [Client thread/INFO] [STDERR/HydCraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    [14:20:42] [Client thread/WARN] [HydCraft/HydCraft]: Got empty message from update. Either not connected to internet or something fishy is going on!

I'm assuming this is due to the main site being down, but am wondering if it is possible to reduce the time out delay, as 5 minutes seems way too long.

**Comment by K-4U** [comment]
We've disabled the update checker in the next update.
(God i've been slow with replying :( )
