### ISSUE TITLE
Updated to 2.1.246 now crashes on Dedicated Server

### ISSUE THREAD

**Issue by spamenigma** [K-4U/Hydraulicraft#168]
Hi getting the following crash, appears to be ok client, just server not starting.

http://pastebin.com/yyd2HLiV

Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: pressure
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchFieldError: pressure
	at k4unl.minecraft.Hydraulicraft.Hydraulicraft.<clinit>(Hydraulicraft.java:76)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

Thanks

**Comment by K-4U** [comment]
Oh this is stupid. Hang on, releasing a fix soon

**Comment by spamenigma** [comment]
Great! thanks!!

Tested the newer version 2.1.249 and can confirm all appears to work fine.

**Comment by K-4U** [comment]
My pleasure! :)
