### ISSUE TITLE
noCLassDefFounderror Crash

### ISSUE THREAD

**Issue by TechStack** [K-4U/Hydraulicraft#188]
We are using Forge 1722 on a SMP server using hydrolicraft 3.1.48-universal.

A player opened the outter lands portal (thaumcraft) and went to the dimension and it caused a crash.

Posting this heae because the stack trace mentions your classes.

Cheers !
- Tech
  Below is from the crash report:

// I'm sorry, Dave.

Time: 2/9/16 2:16 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/crash/CrashReportCategory$4
        at net.minecraft.crash.CrashReportCategory.func_175750_a(CrashReportCategory.java:242)
        at net.minecraft.world.World.func_180496_d(World.java:523)
        at net.minecraft.world.World.func_175685_c(World.java:452)
        at net.minecraft.world.World.func_175722_b(World.java:407)
        at net.minecraft.world.World.markAndNotifyBlock(World.java:352)
        at net.minecraft.world.World.func_180501_a(World.java:333)
        at net.minecraft.world.World.func_175656_a(World.java:392)
        at k4unl.minecraft.Hydraulicraft.world.WorldGenOil.generate(WorldGenOil.java:46)
        at k4unl.minecraft.Hydraulicraft.world.HCWorldGenerator.generateOverworld(HCWorldGenerator.java:145)
        at k4unl.minecraft.Hydraulicraft.world.HCWorldGenerator.generate(HCWorldGenerator.java:36)
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1081)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
        at net.minecraft.world.World.func_72964_e(World.java:287)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:364)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
        at java.lang.Thread.run(Thread.java:745)

**Comment by K-4U** [comment]
Wow. I'm seriously confused by this issue. It appears to be coming from me, but i also have absolutely no idea how it would be caused. Is the issue easily recreated?

**Comment by TechStack** [comment]
I'll have to get back to you on it.
I'm the server admin (& mod dev myself) & wasn't on when it happened. 
2nd & 3rd crashes when user logged in are still no Class Def found errors but the stack trace is different.
all have been in the same CrasHreportCategory ... may be a forge issue possibly.

**Comment by HenryLoenwind** [comment]
may be related: MinecraftForge/MinecraftForge#2421

**Comment by K-4U** [comment]
So far i'm writing this off as an issue in MC Forge. Waiting for some more info from their end.

**Comment by TechStack** [comment]
Yeah they put a patch in to forge that may fix it I hope to get it on my
server this weekend to confirm it resolved it.

**Comment by LabGoblin** [comment]
https://www.dropbox.com/s/qfghk2o6s6ro4q7/Capture.PNG?dl=0 thats the modlist i tested the following with.

the bug is in your oil generator. if i disable Hc oil it stops. server owners will need to delete the dim-42 before someone tries to go there though.

the dimension is FULL of some pretty bedrock block from tc instead of air and then it generate the dungeon after.

**Comment by K-4U** [comment]
Waiting on new crashlogs for this.

**Comment by LabGoblin** [comment]
https://www.dropbox.com/sh/z5mhwd594bgzeb4/AAAHsqF2hnGcAqqtD_2W6ydoa?dl=0

**Comment by LabGoblin** [comment]
there you go. modlist and crashlog. let me know if you need anymore

**Comment by K-4U** [comment]
Well then, now it sounds a whole lot like thaumcraft doing it...

**Comment by TechStack** [comment]
K-4U...
when we tried to reproduce the error after upgrading to the latest forge it still crashed with 
java.lang.NoClassDefFoundError: net/minecraft/crash/CrashReportCategory$4
but the stack trace did not point back to hydraulicraft.

Also we have had other cases where it crashes by reproducing the same steps 
with java.lang.NoClassDefFoundError: net/minecraft/crash/CrashReportCategory$4
by going into the TC dimension but the stack trace was a different mod.

It seems that it may still be an issue with forge or some other coremod modifying things.
for now we are staying out of the TC dimension on my server.

I'd be OK if the issue is closed on here until we can get more info in a crash report where the Crash report class itself is not the crashing too.... until then we wont know exactlly where the root cause of the issue is.

The crash report that bushbaby1234 posted seems unrelated... unless he was able to bypass the NoclassDefFoundError somehow.

**Comment by LabGoblin** [comment]
if you turn off oil gen in HC you can enter the dimension without error.
