### ISSUE TITLE
[CRASH] [1.8.9] Attempted to update a multipart at an illegal position!

### ISSUE THREAD

**Issue by hron84** [K-4U/Hydraulicraft#217]
```
java.lang.IllegalStateException: Attempted to update a multipart at an illegal position!
    at mcmultipart.network.MessageMultipartChange.newPacket(MessageMultipartChange.java:147)
    at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:300)
    at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:291)
    at k4unl.minecraft.Hydraulicraft.multipart.PartHose.updateNeighborInfo(PartHose.java:440)
    at k4unl.minecraft.Hydraulicraft.multipart.PartHose.func_73660_a(PartHose.java:203)
    at mcmultipart.block.TileMultipart.func_73660_a(TileMultipart.java:152)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
```
- HydCraft{1.8.9-3.1.65}
- mcmultipart{1.0.7} [MCMultiPart]

(I'm using a basic HydCraft ore processing line, one medium pressure pump+medium reservoir, crusher, friction incinerator. The bug is happened a little bit after i "smelt" a netherrack into a nether brick (I had a time to pull it out and start climbing on a ladder, and boom).

**Comment by hron84** [comment]
Thank you very much for this fix!
