### ISSUE TITLE
Still having bacon issue (with Greg?)

### ISSUE THREAD

**Issue by BlazingGamer** [K-4U/Hydraulicraft#226]
When loading HydCraft gives me this issue:
`[19:43:34] [Client thread/WARN] [FML/HydCraft]: ****************************************
[19:43:34] [Client thread/WARN] [FML/HydCraft]: * A broken ore dictionary registration with name bacon has occurred. It adds an item (type: class k4unl.minecraft.Hydraulicraft.items.ItemBacon) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Hydraulicraft report it to them!
[19:43:34] [Client thread/WARN] [FML/HydCraft]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:43:34] [Client thread/WARN] [FML/HydCraft]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:43:34] [Client thread/WARN] [FML/HydCraft]: *  at k4unl.minecraft.Hydraulicraft.items.HCItems.registerItems(HCItems.java:154)
[19:43:34] [Client thread/WARN] [FML/HydCraft]: *  at k4unl.minecraft.Hydraulicraft.items.HCItems.init(HCItems.java:108)
[19:43:34] [Client thread/WARN] [FML/HydCraft]: *  at k4unl.minecraft.Hydraulicraft.Hydraulicraft.preInit(Hydraulicraft.java:98)
[19:43:34] [Client thread/WARN] [FML/HydCraft]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[19:43:34] [Client thread/WARN] [FML/HydCraft]: ****************************************`
The same as #164 but in latest version.
### Forge and Minecraft version

MC 1.7.10, Forge 1566. GregTech 6.02.06 (latest, in case if this matters)
### Hydraulicraft version and build number

HydCraft 2.1.253 (think this is latest for 1.7)
### K4Lib version

K4 Lib 0.1.57

**Comment by K-4U** [comment]
Sorry, but support for 1.7.10 is over. Time to switch to 1.10!
